### ISSUE TITLE
Connecting plinky rev2 not possible

### ISSUE THREAD

**Issue by ch-one** [plinkysynth/editor#5]
I tried to connect with „Plinky editor“ (Chromium on macOS and Ubuntu) to my plinky rev2 hardware with firmware version 0.9x. The browser dialog to select a device does not show plinky. When checking for usb devices via `lsusb` the vendor id `cafe` is listed. This is usb interface of plinky, right?

Is there any known issue?

**Comment by mmalex** [comment]
Hmm thats odd, Ive not seen it fail to come up before. I am not that
experienced with the webusb stuff, especially the browser side, so I'm not
sure how to debug for you. thanks for checking lsusb - so the device end is
'happy'. maybe is there something in the log? I think on chrome it is
chrome://device-log . I did once on windows have it fail to connect, but
restarting the machine fixed it...

**Comment by ch-one** [comment]
Thanks for your advice. With it I made some progress.

# On Linux
With chrome://device-log I found that chrome did not have permission to access usb devices. With the following udev rule, I was able to give chrome the missing permission:

`SUBSYSTEM=="usb", ATTRS{idVendor}=="cafe", MODE="0660", GROUP="plugdev"`

I'm not an udev expert, so I'm not sure if this has any caveats, but it looks ok to me. But also not convenient 😬

A documentation could maybe help. 

# On macOS
I realized, that Plinky hardware is not detected on my Mac, and therefore is never recognized by chrome. Not sure what the problem is, but for now I'm happy, that it works on my Linux machine.
